name: events_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  #  Class helpers
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4

  # Firebase
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0

  # Other
  get_it: ^7.6.7
  go_router: ^14.1.1
  dartz: ^0.10.1
  oktoast: ^3.4.0
  calendar_date_picker2: ^1.1.8
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  source_gen: ^1.2.7
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

flutter:
  uses-material-design: true
